dsas:
  logging:
    dir: ${HOME}
    fileName: ds-assignment
    level: DEBUG
    maxNumFiles: 10
    maxFileSize: 10MB
  upload.dir: ${HOME}

server.port: 6010
spring:
  data:
    mongodb:
      port: 27000
  jackson:
      date-format: yyyy-MM-dd'T'HH:mm:ss.SSSZ
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB